# Generated by Django 3.1.4 on 2020-12-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201208_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
